[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.16"

[fmt]
line_length = 100
tab_width = 4
func_attrs_with_params_multiline = true
ignore = ["lib/**"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config